### ISSUE TITLE
Is it possible to make a diagram for collectLatest()?

### ISSUE THREAD

**Issue by YogeshUmeshVaity** [rougsig/flowmarbles#4]
Mentioned [here](https://kotlinlang.org/docs/reference/coroutines/flow.html#processing-the-latest-value) in the documentation.

**Comment by rougsig** [comment]
In fact it's same as [transformLatest](https://flowmarbles.com/#transformLatest)

**Comment by YogeshUmeshVaity** [comment]
Alright, really appreciate your efforts making this site!

**Comment by rougsig** [comment]
Ok. Do you actually want this feature? I think that feature is redundant.

**Comment by YogeshUmeshVaity** [comment]
> Ok. Do you actually want this feature? I think that feature is redundant.

I personally think that since it's mentioned in the official language guide, people will be curious to know how it looks in the marble diagram, just like how I searched for it. So, it should be there. Having listed all the operators mentioned in the official documentation will increase the efficacy of flowmarbles.com.

**Comment by rougsig** [comment]
Yes it's true, but `collect` `collectLatest` is not an operator it's a collector. We can see it [here](https://github.com/Kotlin/kotlinx.coroutines/tree/master/kotlinx-coroutines-core/common/src/flow)

**Comment by YogeshUmeshVaity** [comment]
> Yes it's true, but `collect` `collectLatest` is not an operator it's a collector. We can see it [here](https://github.com/Kotlin/kotlinx.coroutines/tree/master/kotlinx-coroutines-core/common/src/flow)

I think you are right.
