### ISSUE TITLE
Feature: link to official docs

### ISSUE THREAD

**Issue by erikhuizinga** [rougsig/flowmarbles#5]
The [official docs](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/index.html) are a valuable resource to understand some of the behavioural details of certain operators or their combinations. The docs alone or a marble diagram alone provide only half of the story. The suggestion is to show (part of) the documentation text under the diagram. General flow docs might be useful too, e.g. to explain flow completion.

**Comment by ifarhanpatel** [comment]
what's the update on this? It is the first thing I was looking for after seeing the diagram. Seems like a legit request.

**Comment by erikhuizinga** [comment]
As an extension to this feature request (likely worth a separate issue):

Add the ability to specify the coroutines library used. And possibly the platform too (in case of different possibilities or behaviour on different platforms).

Then the behaviour can be tailored to the version that the user wants to see in action. The (links to) docs could also target the corresponding version of the docs.

**Comment by rougsig** [comment]
> As an extension to this feature request (likely worth a separate issue):
> 
> Add the ability to specify the coroutines library used. And possibly the platform too (in case of different possibilities or behaviour on different platforms).
> 
> Then the behaviour can be tailored to the version that the user wants to see in action. The (links to) docs could also target the corresponding version of the docs.

About version, uups i dont put used version on UI. Will add it. 

Marbles are rendering in runtime, with js. I think now its not nessesary, behaviour should be same on all platforms.

About docs, has some throubles with adding it to site, will check if is exits now on this week.

**Comment by rougsig** [comment]
some throubles with deploy. But you can check new version with 502 docs :smile:
https://flowmarbles.com/new/#distinctUntilChanged

**Comment by rougsig** [comment]
Done. Check it out.

**Comment by hrach** [comment]
It is broken a little in Firefox.
![obrazek](https://user-images.githubusercontent.com/284263/121895169-382c3180-cd20-11eb-8615-470b54afab1a.png)

**Comment by rougsig** [comment]
Should be fixed now. 
That problem with browser cache. You can manually fix that problem with force refresh page.

**Comment by erikhuizinga** [comment]
Very nice! Nice job. One additional wish would be to link to the documentation page for the operator, next to the [Kotlin docs](https://kotlin.github.io/kotlinx.coroutines/) link.

Something like:

[`distinctUntilChanged`](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/distinct-until-changed.html) docs provided by [Kotlin coroutines docs](https://kotlin.github.io/kotlinx.coroutines/).

**Comment by rougsig** [comment]
Added.
![image](https://user-images.githubusercontent.com/18681794/124533812-51059f80-de13-11eb-8f35-ecc6160d1b54.png)
