### ISSUE TITLE
Understanding the groups

### ISSUE THREAD

**Issue by kronstein** [rougsig/flowmarbles#7]
Thank you for your work, it is very helpful and I recommend it to my fellow devs.
https://flowmarbles.com/

Still, I have a question and I would appreciate if you clarify the following:

`transform()` function is in `EMITTERS` group.
`transformLatest()` is filed under `MERGE` group.
One may think that `transform()` and `transformLatest()` doing different things, but they serve the same purpose actually, by design.
To make things even more complicated, there is also `TRANSFORM` group.

It's not very straightforward for me to follow the principle of this grouping. How do you decide which group a function belongs to?

**Comment by rougsig** [comment]
Interesting question. I didn't think about the grouping principle at all. When I wrote the menu logic, I looked at the kotlin flow source code.

https://github.com/Kotlin/kotlinx.coroutines/tree/master/kotlinx-coroutines-core/common/src/flow/operators
