### ISSUE TITLE
Doc not found of operator..reduceScan

### ISSUE THREAD

**Issue by brightdanielt** [rougsig/flowmarbles#9]
I clicked link of "Docs provided by Kotlin docs(original)" in https://flowmarbles.com/#scanReduce 
and it show 404 file not found.

**Comment by rougsig** [comment]
Thx for issue!

`scanReduce` was replaced with `runningReduce`. 
https://github.com/Kotlin/kotlinx.coroutines/commit/5e91dc45044b28f8b10d76e231e886b0b7da42f1

I will update the site with new operators.

**Comment by rougsig** [comment]
Done

https://flowmarbles.com/#runningReduce
